application: whpetitionsinfo
version: 1
runtime: go
api_version: go1

handlers:
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  
- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png
  
- url: /updatePending
  script: _go_app
  login: admin
  
- url: /updateResponded
  script: _go_app
  login: admin
  
- url: /.*
  script: _go_app